# Generated by Codex on 2026-04-21

import common.encoder.encoder
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_manage', '0005_resourcemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='actor',
            field=models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='操作者契约'),
        ),
        migrations.AddField(
            model_name='log',
            name='event_name',
            field=models.CharField(db_index=True, default='', max_length=160, verbose_name='审计事件名称'),
        ),
        migrations.AddField(
            model_name='log',
            name='resource',
            field=models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='资源契约'),
        ),
        migrations.AddField(
            model_name='log',
            name='result',
            field=models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='结果契约'),
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='事件时间'),
        ),
    ]
