name: sync2gitee

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/however-yir'
          dst: 'gitee/however-yir'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'LZKB'
          force_update: true
