name: Typos Check
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Create config file
      run: |
        cat <<EOF > typo-check-config.toml
        [files]
        extend-exclude = [
          "**/*_svg",
          "**/migrations/**",
          "**/loopEdge.ts",
          "**/edge.ts",
          "ui/src/components/dynamics-form/items/model/provider-data.ts",
          "ui/src/workflow/common/template.ts",
          "apps/models_provider/impl/tencent_model_provider/model/stt.py",
        ]

        [default.extend-words]
        RTO = "RTO"
        rto = "rto"
        RPO = "RPO"
        rpo = "rpo"
        EOF
    - name: Check spelling
      uses: crate-ci/typos@master
      with:
        config: ./typo-check-config.toml
